jobs:
  include:
    # build-and-deploy stage
    - stage: build-and-deploy
      # Define a template with JAVA
      language: java
      # cache: Add a cache folder to improve build-speed
      cache:
        directories:
        - $HOME/.m2
      # install phase: with maven project packaging a jar is implicit
      # script phase: Copy artefact to build folder to allow upload to S3 bucket
      script:
      - mkdir build
      - cp target/demo-aws-deployment-0.0.1-SNAPSHOT.jar build/app.jar
      
      before_install:
        - chmod +x mvnw
      # Run a set of AWS eb commands to deploy application to AWS (Check for AWS Beanstalk logs to check for creation and deployment)
      before_deploy:
      - chmod +x mvnw
      - export ELASTIC_BEANSTALK_ENV=webapp-${TRAVIS_BRANCH}
      - export ELASTIC_BEANSTALK_LABEL=git-$(git rev-parse --verify HEAD --short)
      - export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/atulkhare/webapp/tree/$(git rev-parse HEAD)
      - docker pull chriscamicas/awscli-awsebcli
      - docker run -e AWS_ACCESS_KEY -e AWS_SECRET_KEY chriscamicas/awscli-awsebcli /bin/sh -c "eb init webapp -p "64bit Amazon Linux 2017.09 v2.6.4 running Java 8" --region "ca-central-1"; eb create Webapp-env --single || true; eb setenv SERVER_PORT=5000"
      after_deploy:
      - rm build/app.jar
      # deploy binary from s3 bucket to beanstalk
      deploy:
      - provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        zip-file: "build/app.jar"
        region: "ap-south-1"
        app: "webapp"
        env: "Webapp-env"
        bucket_name: "elasticbeanstalk-ap-south-1-274749375098"
        skip_cleanup: true
        only_create_app_version: false