sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t atulkhare/webapp -f Dockerfile.dev .

script:
  - docker run -e CI=true atulkhare/webapp mvn -Dtest="*.*" test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "webapp"
  env: "Webapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-274749375098"
  bucket_path: "webapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY